apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-admin
  namespace: python-tool
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
